query Espacios{
  espacios{
    id
    nombre
    img
    ubicacion
  }
}

query Espacio($id:Int!) {
  espacio(id: $id){
    id
    Eventos{
      id
      nombre
      fecha
      img
    }
  }
}

query Evento($id: Int!) {
  evento(id: $id) {
    id
    nombre
    horarios
    Tipo_evento{
      id
      nombre
    }
    fecha
    pases
    sala
    duracion
    Espacio{
      id
      nombre
      ubicacion

    }
    director
    sinopsis
    trailer
    reparto
    precio
    img
  }
}
query Eventos {
  eventos {
    id
    nombre
    horarios
    fecha
    img
    Espacio{
      ubicacion
    }
    Tipo_evento{
      nombre
    }
  }
}
